services:
  - type: web
    name: TrucoMania
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3000
      - key: CLIENT_URL
        value: https://trucomania.onrender.com
